# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fractureP.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridTabWidget_5 = QtWidgets.QTabWidget(self.centralwidget)
        self.gridTabWidget_5.setGeometry(QtCore.QRect(10, 0, 941, 901))
        self.gridTabWidget_5.setObjectName("gridTabWidget_5")
        self.tab_reflect_3 = QtWidgets.QWidget()
        self.tab_reflect_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tab_reflect_3.setObjectName("tab_reflect_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_reflect_3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.tab_reflect_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.widget = QtWidgets.QWidget(self.frame_6)
        self.widget.setGeometry(QtCore.QRect(10, 10, 901, 381))
        self.widget.setObjectName("widget")
        self.gridLayout_9.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_reflect_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_33 = QtWidgets.QLabel(self.frame_4)
        self.label_33.setGeometry(QtCore.QRect(470, 210, 158, 29))
        self.label_33.setObjectName("label_33")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setGeometry(QtCore.QRect(660, 20, 161, 151))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 141, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.doubleSpinBox_DT = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_DT.setDecimals(3)
        self.doubleSpinBox_DT.setMaximum(1.0)
        self.doubleSpinBox_DT.setSingleStep(0.01)
        self.doubleSpinBox_DT.setObjectName("doubleSpinBox_DT")
        self.gridLayout_5.addWidget(self.doubleSpinBox_DT, 1, 1, 1, 1)
        self.verticalSlider_DT = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.verticalSlider_DT.setMaximum(1000)
        self.verticalSlider_DT.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_DT.setObjectName("verticalSlider_DT")
        self.gridLayout_5.addWidget(self.verticalSlider_DT, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalSlider_DN = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.verticalSlider_DN.setMaximum(1000)
        self.verticalSlider_DN.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_DN.setObjectName("verticalSlider_DN")
        self.gridLayout_5.addWidget(self.verticalSlider_DN, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox_DN = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_DN.setDecimals(3)
        self.doubleSpinBox_DN.setMaximum(1.0)
        self.doubleSpinBox_DN.setSingleStep(0.01)
        self.doubleSpinBox_DN.setObjectName("doubleSpinBox_DN")
        self.gridLayout_5.addWidget(self.doubleSpinBox_DN, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(670, 200, 221, 51))
        self.frame_2.setStyleSheet("background-color: rgb(234, 226, 228);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 0, 128, 52))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.split_box45_90 = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.split_box45_90.setStyleSheet("color: rgb(255, 255, 0);")
        self.split_box45_90.setObjectName("split_box45_90")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.split_box45_90)
        self.split_box0_45 = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.split_box0_45.setStyleSheet("color: rgb(85, 0, 255);")
        self.split_box0_45.setObjectName("split_box0_45")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.split_box0_45)
        self.split_box30_60 = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.split_box30_60.setStyleSheet("color: rgb(0, 255, 0);")
        self.split_box30_60.setObjectName("split_box30_60")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.split_box30_60)
        self.split_box0_90 = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.split_box0_90.setStyleSheet("color: rgb(255, 0, 0);")
        self.split_box0_90.setObjectName("split_box0_90")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.split_box0_90)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 71, 51))
        self.label_18.setObjectName("label_18")
        self.verticalFrame_5 = QtWidgets.QFrame(self.frame_4)
        self.verticalFrame_5.setGeometry(QtCore.QRect(510, 20, 131, 135))
        self.verticalFrame_5.setStyleSheet("")
        self.verticalFrame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_26 = QtWidgets.QLabel(self.verticalFrame_5)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.verticalFrame_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalFrame_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.doubleSpinBox_bulk = QtWidgets.QDoubleSpinBox(self.verticalFrame_5)
        self.doubleSpinBox_bulk.setObjectName("doubleSpinBox_bulk")
        self.gridLayout_3.addWidget(self.doubleSpinBox_bulk, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalFrame_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.verticalFrame_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 1, 1, 1)
        self.doubleSpinBox_shear = QtWidgets.QDoubleSpinBox(self.verticalFrame_5)
        self.doubleSpinBox_shear.setObjectName("doubleSpinBox_shear")
        self.gridLayout_3.addWidget(self.doubleSpinBox_shear, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 299, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 4, 0, 1, 1)
        self.spinBox_vs1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_vs1.setMinimum(1)
        self.spinBox_vs1.setMaximum(1000000000)
        self.spinBox_vs1.setObjectName("spinBox_vs1")
        self.gridLayout.addWidget(self.spinBox_vs1, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 1, 1, 1)
        self.spinBox_p1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_p1.setMinimum(1)
        self.spinBox_p1.setMaximum(1000000000)
        self.spinBox_p1.setObjectName("spinBox_p1")
        self.gridLayout.addWidget(self.spinBox_p1, 3, 1, 1, 1)
        self.spinBox_vp2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_vp2.setMinimum(1)
        self.spinBox_vp2.setMaximum(1000000000)
        self.spinBox_vp2.setObjectName("spinBox_vp2")
        self.gridLayout.addWidget(self.spinBox_vp2, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.spinBox_vs2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_vs2.setMinimum(1)
        self.spinBox_vs2.setMaximum(1000000000)
        self.spinBox_vs2.setObjectName("spinBox_vs2")
        self.gridLayout.addWidget(self.spinBox_vs2, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.spinBox_thick = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_thick.setMaximum(100000)
        self.spinBox_thick.setProperty("value", 1000)
        self.spinBox_thick.setObjectName("spinBox_thick")
        self.gridLayout.addWidget(self.spinBox_thick, 4, 1, 1, 1)
        self.spinBox_vp1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_vp1.setFrame(True)
        self.spinBox_vp1.setMinimum(1)
        self.spinBox_vp1.setMaximum(1000000000)
        self.spinBox_vp1.setObjectName("spinBox_vp1")
        self.gridLayout.addWidget(self.spinBox_vp1, 1, 1, 1, 1)
        self.spinBox_p2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_p2.setMinimum(1)
        self.spinBox_p2.setMaximum(1000000000)
        self.spinBox_p2.setObjectName("spinBox_p2")
        self.gridLayout.addWidget(self.spinBox_p2, 3, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setGeometry(QtCore.QRect(340, 10, 151, 171))
        self.frame.setStyleSheet("gridline-color: rgb(255, 170, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(20, 10, 111, 20))
        self.label_25.setObjectName("label_25")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 137, 76))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.doubleSpinBox_aspect = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_aspect.setDecimals(3)
        self.doubleSpinBox_aspect.setMinimum(0.001)
        self.doubleSpinBox_aspect.setMaximum(100.0)
        self.doubleSpinBox_aspect.setSingleStep(0.01)
        self.doubleSpinBox_aspect.setObjectName("doubleSpinBox_aspect")
        self.verticalLayout_4.addWidget(self.doubleSpinBox_aspect)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.spinBox_fract = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox_fract.setMaximum(100)
        self.spinBox_fract.setObjectName("spinBox_fract")
        self.verticalLayout_5.addWidget(self.spinBox_fract)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalSlider_fract = QtWidgets.QSlider(self.frame)
        self.verticalSlider_fract.setGeometry(QtCore.QRect(100, 110, 20, 51))
        self.verticalSlider_fract.setMaximum(100)
        self.verticalSlider_fract.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_fract.setObjectName("verticalSlider_fract")
        self.verticalSlider_aspect = QtWidgets.QSlider(self.frame)
        self.verticalSlider_aspect.setGeometry(QtCore.QRect(40, 110, 20, 51))
        self.verticalSlider_aspect.setMaximum(10000)
        self.verticalSlider_aspect.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_aspect.setObjectName("verticalSlider_aspect")
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setGeometry(QtCore.QRect(0, 190, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(585, 212, 20, 16))
        self.label_17.setObjectName("label_17")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 210, 411, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30, 0, QtCore.Qt.AlignHCenter)
        self.spinBox_ngeo = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_ngeo.setMaximum(10000)
        self.spinBox_ngeo.setProperty("value", 96)
        self.spinBox_ngeo.setObjectName("spinBox_ngeo")
        self.horizontalLayout_2.addWidget(self.spinBox_ngeo)
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31, 0, QtCore.Qt.AlignHCenter)
        self.spinBox_rmin = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_rmin.setMaximum(10000)
        self.spinBox_rmin.setProperty("value", 20)
        self.spinBox_rmin.setObjectName("spinBox_rmin")
        self.horizontalLayout_2.addWidget(self.spinBox_rmin)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_2.addWidget(self.label_32)
        self.spinBox_rstep = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_rstep.setMaximum(10000)
        self.spinBox_rstep.setProperty("value", 20)
        self.spinBox_rstep.setObjectName("spinBox_rstep")
        self.horizontalLayout_2.addWidget(self.spinBox_rstep)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(840, 20, 64, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.doubleSpinBox_d = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_d.setDecimals(3)
        self.doubleSpinBox_d.setSingleStep(0.1)
        self.doubleSpinBox_d.setObjectName("doubleSpinBox_d")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_d)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.doubleSpinBox_e = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_e.setDecimals(3)
        self.doubleSpinBox_e.setSingleStep(0.1)
        self.doubleSpinBox_e.setObjectName("doubleSpinBox_e")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_e)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_y.setDecimals(3)
        self.doubleSpinBox_y.setSingleStep(0.1)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_y)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 260, 881, 31))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 859, 29))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_solo = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_solo.setObjectName("checkBox_solo")
        self.horizontalLayout.addWidget(self.checkBox_solo)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.solo_espessura = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.solo_espessura.setEnabled(False)
        self.solo_espessura.setFrame(True)
        self.solo_espessura.setMinimum(1)
        self.solo_espessura.setMaximum(1000000000)
        self.solo_espessura.setProperty("value", 6)
        self.solo_espessura.setObjectName("solo_espessura")
        self.horizontalLayout.addWidget(self.solo_espessura)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout.addWidget(self.label_35)
        self.solo_densidade = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.solo_densidade.setEnabled(False)
        self.solo_densidade.setMaximum(1000000000)
        self.solo_densidade.setProperty("value", 2500)
        self.solo_densidade.setObjectName("solo_densidade")
        self.horizontalLayout.addWidget(self.solo_densidade)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout.addWidget(self.label_36)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22, 0, QtCore.Qt.AlignRight)
        self.solo_vp = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.solo_vp.setEnabled(False)
        self.solo_vp.setFrame(True)
        self.solo_vp.setMinimum(1)
        self.solo_vp.setMaximum(1000000000)
        self.solo_vp.setProperty("value", 380)
        self.solo_vp.setObjectName("solo_vp")
        self.horizontalLayout.addWidget(self.solo_vp)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20, 0, QtCore.Qt.AlignLeft)
        self.label_48 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout.addWidget(self.label_48)
        self.solo_vs = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.solo_vs.setEnabled(False)
        self.solo_vs.setFrame(True)
        self.solo_vs.setMinimum(1)
        self.solo_vs.setMaximum(1000000000)
        self.solo_vs.setProperty("value", 114)
        self.solo_vs.setObjectName("solo_vs")
        self.horizontalLayout.addWidget(self.solo_vs)
        self.label_49 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout.addWidget(self.label_49)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_9.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridTabWidget_5.addTab(self.tab_reflect_3, "")
        self.tab_anray_3 = QtWidgets.QWidget()
        self.tab_anray_3.setObjectName("tab_anray_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_anray_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(710, 0, 200, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.tabWidget = QtWidgets.QTabWidget(self.tab_anray_3)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 911, 621))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_anray = QtWidgets.QWidget(self.tab_4)
        self.widget_anray.setGeometry(QtCore.QRect(0, 50, 911, 611))
        self.widget_anray.setObjectName("widget_anray")
        self.frame_7 = QtWidgets.QFrame(self.tab_4)
        self.frame_7.setEnabled(False)
        self.frame_7.setGeometry(QtCore.QRect(330, 0, 221, 51))
        self.frame_7.setStyleSheet("background-color: rgb(234, 226, 228);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame_7)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(90, 0, 128, 52))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.split_box_anray_45_90 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.split_box_anray_45_90.setStyleSheet("color: rgb(255, 255, 0);")
        self.split_box_anray_45_90.setObjectName("split_box_anray_45_90")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.split_box_anray_45_90)
        self.split_box_anray_0_45 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.split_box_anray_0_45.setStyleSheet("color: rgb(85, 0, 255);")
        self.split_box_anray_0_45.setObjectName("split_box_anray_0_45")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.split_box_anray_0_45)
        self.split_box_anray_30_60 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.split_box_anray_30_60.setStyleSheet("color: rgb(0, 255, 0);")
        self.split_box_anray_30_60.setObjectName("split_box_anray_30_60")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.split_box_anray_30_60)
        self.split_box_anray_0_90 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.split_box_anray_0_90.setStyleSheet("color: rgb(255, 0, 0);")
        self.split_box_anray_0_90.setObjectName("split_box_anray_0_90")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.split_box_anray_0_90)
        self.label_34 = QtWidgets.QLabel(self.frame_7)
        self.label_34.setGeometry(QtCore.QRect(10, 0, 71, 51))
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_anray2 = QtWidgets.QWidget(self.tab_5)
        self.widget_anray2.setGeometry(QtCore.QRect(0, 0, 911, 661))
        self.widget_anray2.setObjectName("widget_anray2")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridTabWidget_5.addTab(self.tab_anray_3, "")
        self.tab_su = QtWidgets.QWidget()
        self.tab_su.setObjectName("tab_su")
        self.frame_8 = QtWidgets.QFrame(self.tab_su)
        self.frame_8.setEnabled(True)
        self.frame_8.setGeometry(QtCore.QRect(140, 10, 701, 171))
        self.frame_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_8)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 124, 95))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_tmax = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_tmax.setDecimals(3)
        self.doubleSpinBox_tmax.setSingleStep(0.1)
        self.doubleSpinBox_tmax.setProperty("value", 0.4)
        self.doubleSpinBox_tmax.setObjectName("doubleSpinBox_tmax")
        self.gridLayout_2.addWidget(self.doubleSpinBox_tmax, 1, 0, 1, 1)
        self.doubleSpinBox_tmin = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_tmin.setDecimals(3)
        self.doubleSpinBox_tmin.setMinimum(0.0)
        self.doubleSpinBox_tmin.setSingleStep(0.1)
        self.doubleSpinBox_tmin.setObjectName("doubleSpinBox_tmin")
        self.gridLayout_2.addWidget(self.doubleSpinBox_tmin, 0, 0, 1, 1)
        self.Tmin = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Tmin.setObjectName("Tmin")
        self.gridLayout_2.addWidget(self.Tmin, 0, 1, 1, 1)
        self.Tmax = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Tmax.setObjectName("Tmax")
        self.gridLayout_2.addWidget(self.Tmax, 1, 1, 1, 1)
        self.doubleSpinBox_dt = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_dt.setDecimals(4)
        self.doubleSpinBox_dt.setSingleStep(0.001)
        self.doubleSpinBox_dt.setProperty("value", 0.001)
        self.doubleSpinBox_dt.setObjectName("doubleSpinBox_dt")
        self.gridLayout_2.addWidget(self.doubleSpinBox_dt, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 1, 1, 1)
        self.sismo_button = QtWidgets.QPushButton(self.frame_8)
        self.sismo_button.setEnabled(False)
        self.sismo_button.setGeometry(QtCore.QRect(550, 90, 91, 27))
        self.sismo_button.setObjectName("sismo_button")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setEnabled(False)
        self.frame_9.setGeometry(QtCore.QRect(150, 10, 331, 21))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_9)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 311, 24))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_41 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_4.addWidget(self.label_41)
        self.radioButton_0 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_0.setChecked(True)
        self.radioButton_0.setObjectName("radioButton_0")
        self.horizontalLayout_4.addWidget(self.radioButton_0)
        self.radioButton_30 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_30.setObjectName("radioButton_30")
        self.horizontalLayout_4.addWidget(self.radioButton_30)
        self.radioButton_45 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_45.setObjectName("radioButton_45")
        self.horizontalLayout_4.addWidget(self.radioButton_45)
        self.radioButton_60 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_60.setObjectName("radioButton_60")
        self.horizontalLayout_4.addWidget(self.radioButton_60)
        self.radioButton_90 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_90.setObjectName("radioButton_90")
        self.horizontalLayout_4.addWidget(self.radioButton_90, 0, QtCore.Qt.AlignHCenter)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_8)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(520, 30, 141, 52))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox_freq = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.doubleSpinBox_freq.setProperty("value", 50.0)
        self.doubleSpinBox_freq.setObjectName("doubleSpinBox_freq")
        self.gridLayout_7.addWidget(self.doubleSpinBox_freq, 1, 0, 1, 1)
        self.doubleSpinBox_gama = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.doubleSpinBox_gama.setProperty("value", 4.0)
        self.doubleSpinBox_gama.setObjectName("doubleSpinBox_gama")
        self.gridLayout_7.addWidget(self.doubleSpinBox_gama, 1, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_8)
        self.label_44.setGeometry(QtCore.QRect(560, 10, 56, 20))
        self.label_44.setObjectName("label_44")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(160, 40, 311, 121))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName("frame_10")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_10)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(90, 10, 201, 91))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_normx = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_normx.setText("")
        self.radioButton_normx.setObjectName("radioButton_normx")
        self.gridLayout_4.addWidget(self.radioButton_normx, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_x_max = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_x_max.setObjectName("label_x_max")
        self.gridLayout_4.addWidget(self.label_x_max, 1, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 0, 0, 1, 1)
        self.radioButton_norm_def = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_norm_def.setText("")
        self.radioButton_norm_def.setChecked(True)
        self.radioButton_norm_def.setObjectName("radioButton_norm_def")
        self.gridLayout_4.addWidget(self.radioButton_norm_def, 0, 1, 1, 1)
        self.doubleSpinBox_normalf = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.doubleSpinBox_normalf.setDecimals(4)
        self.doubleSpinBox_normalf.setMaximum(10000000.0)
        self.doubleSpinBox_normalf.setProperty("value", 1.0)
        self.doubleSpinBox_normalf.setObjectName("doubleSpinBox_normalf")
        self.gridLayout_4.addWidget(self.doubleSpinBox_normalf, 0, 2, 1, 1)
        self.label_z_max = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_z_max.setObjectName("label_z_max")
        self.gridLayout_4.addWidget(self.label_z_max, 2, 2, 1, 1)
        self.radioButton_normz = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        self.radioButton_normz.setText("")
        self.radioButton_normz.setObjectName("radioButton_normz")
        self.gridLayout_4.addWidget(self.radioButton_normz, 2, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_10)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 71, 41))
        self.label_37.setAutoFillBackground(True)
        self.label_37.setObjectName("label_37")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setGeometry(QtCore.QRect(480, 120, 211, 41))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setLineWidth(0)
        self.frame_12.setObjectName("frame_12")
        self.checkBox_solo_sismo2 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_solo_sismo2.setEnabled(False)
        self.checkBox_solo_sismo2.setGeometry(QtCore.QRect(30, 20, 21, 22))
        self.checkBox_solo_sismo2.setText("")
        self.checkBox_solo_sismo2.setObjectName("checkBox_solo_sismo2")
        self.label_47 = QtWidgets.QLabel(self.frame_12)
        self.label_47.setEnabled(False)
        self.label_47.setGeometry(QtCore.QRect(40, 20, 161, 20))
        self.label_47.setLineWidth(0)
        self.label_47.setObjectName("label_47")
        self.checkBox_solo_sismo = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_solo_sismo.setEnabled(False)
        self.checkBox_solo_sismo.setGeometry(QtCore.QRect(0, 0, 131, 21))
        self.checkBox_solo_sismo.setObjectName("checkBox_solo_sismo")
        self.widget_sismo = QtWidgets.QWidget(self.tab_su)
        self.widget_sismo.setGeometry(QtCore.QRect(10, 200, 921, 481))
        self.widget_sismo.setObjectName("widget_sismo")
        self.gridTabWidget_5.addTab(self.tab_su, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_sismo2 = QtWidgets.QWidget(self.tab)
        self.widget_sismo2.setGeometry(QtCore.QRect(20, 60, 921, 591))
        self.widget_sismo2.setObjectName("widget_sismo2")
        self.frame_11 = QtWidgets.QFrame(self.tab)
        self.frame_11.setEnabled(False)
        self.frame_11.setGeometry(QtCore.QRect(600, 10, 221, 51))
        self.frame_11.setStyleSheet("background-color: rgb(234, 226, 228);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(0)
        self.frame_11.setObjectName("frame_11")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame_11)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(90, 0, 128, 52))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.radio_sismo_0_90 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radio_sismo_0_90.setStyleSheet("")
        self.radio_sismo_0_90.setChecked(True)
        self.radio_sismo_0_90.setObjectName("radio_sismo_0_90")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radio_sismo_0_90)
        self.radio_sismo_45_90 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radio_sismo_45_90.setStyleSheet("")
        self.radio_sismo_45_90.setObjectName("radio_sismo_45_90")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radio_sismo_45_90)
        self.radio_sismo_0_45 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radio_sismo_0_45.setStyleSheet("")
        self.radio_sismo_0_45.setObjectName("radio_sismo_0_45")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radio_sismo_0_45)
        self.radio_sismo_30_60 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radio_sismo_30_60.setStyleSheet("")
        self.radio_sismo_30_60.setObjectName("radio_sismo_30_60")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radio_sismo_30_60)
        self.label_46 = QtWidgets.QLabel(self.frame_11)
        self.label_46.setGeometry(QtCore.QRect(10, 0, 71, 51))
        self.label_46.setObjectName("label_46")
        self.frame_13 = QtWidgets.QFrame(self.tab)
        self.frame_13.setEnabled(False)
        self.frame_13.setGeometry(QtCore.QRect(260, 20, 291, 41))
        self.frame_13.setAutoFillBackground(False)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_13)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 0, 241, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_50 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_3.addWidget(self.label_50)
        self.radioButton_plot_x = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_plot_x.setChecked(True)
        self.radioButton_plot_x.setObjectName("radioButton_plot_x")
        self.horizontalLayout_3.addWidget(self.radioButton_plot_x)
        self.radioButton_plot_z = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_plot_z.setObjectName("radioButton_plot_z")
        self.horizontalLayout_3.addWidget(self.radioButton_plot_z)
        self.frame_14 = QtWidgets.QFrame(self.tab)
        self.frame_14.setEnabled(False)
        self.frame_14.setGeometry(QtCore.QRect(100, 10, 121, 51))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.frame_14)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 0, 101, 51))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.az_tmax = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.az_tmax.setSingleStep(0.01)
        self.az_tmax.setObjectName("az_tmax")
        self.gridLayout_8.addWidget(self.az_tmax, 1, 0, 1, 1)
        self.az_tmin = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.az_tmin.setSingleStep(0.01)
        self.az_tmin.setObjectName("az_tmin")
        self.gridLayout_8.addWidget(self.az_tmin, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 1, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 0, 1, 1, 1)
        self.gridTabWidget_5.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.gridTabWidget_5.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ondas P-S"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p>Ângulo crítico</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DN</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DT</span></p></body></html>"))
        self.split_box45_90.setText(_translate("MainWindow", "45/90"))
        self.split_box0_45.setText(_translate("MainWindow", "0/45"))
        self.split_box30_60.setText(_translate("MainWindow", "30/60"))
        self.split_box0_90.setText(_translate("MainWindow", "0/90"))
        self.label_18.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>10%</p><p>spit</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:600;\">10%<br/>Separação</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600;\">Prop. preenchimento</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">*10</span><span style=\" font-size:8pt; font-style:italic; vertical-align:super;\">9 </span><span style=\" font-size:8pt; font-style:italic;\">Pa</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Shear</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Bulk</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">*10</span><span style=\" font-size:8pt; font-style:italic; vertical-align:super;\">9 </span><span style=\" font-size:8pt; font-style:italic;\">Pa</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Espessura (m)</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">m/s</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Camada 1 <br/></span><span style=\" font-weight:600; vertical-align:sub;\">Isotrópica</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Camada 2 <br/></span><span style=\" font-weight:600; vertical-align:sub;\">HTI</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VP</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VS</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">m/s</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Densidade</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">kg/m</span><span style=\" font-size:8pt; font-style:italic; vertical-align:super;\">3</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Prop. fraturas</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-style:italic;\">Razão de<br/> aspecto</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-style:italic;\">Densidade<br/>fraturamento<br/>(%)</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">         o</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>n<span style=\" vertical-align:super;\">o</span>geo</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p>d<span style=\" vertical-align:sub;\">min</span>(m)</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p>d<span style=\" vertical-align:sub;\">step</span>(m)</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">|d</span><span style=\" font-size:8pt; vertical-align:super;\">v</span><span style=\" font-size:8pt;\">|</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">|e</span><span style=\" font-size:8pt; vertical-align:super;\">v</span><span style=\" font-size:8pt;\">|</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">|y</span><span style=\" font-size:8pt; vertical-align:super;\">v</span><span style=\" font-size:8pt;\">|</span></p></body></html>"))
        self.checkBox_solo.setText(_translate("MainWindow", "Solo"))
        self.label_19.setText(_translate("MainWindow", "Espessura"))
        self.label_21.setText(_translate("MainWindow", "(m)"))
        self.label_35.setText(_translate("MainWindow", "densidade"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">(kg/m</span><span style=\" font-size:8pt; font-style:italic; vertical-align:super;\">3</span><span style=\" font-size:8pt; font-style:italic;\">)</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Vp"))
        self.label_20.setText(_translate("MainWindow", "(m/s)"))
        self.label_48.setText(_translate("MainWindow", "Vs"))
        self.label_49.setText(_translate("MainWindow", "(m/s)"))
        self.pushButton_2.setText(_translate("MainWindow", "Plot"))
        self.gridTabWidget_5.setTabText(self.gridTabWidget_5.indexOf(self.tab_reflect_3), _translate("MainWindow", "Coeficiente de reflexão"))
        self.pushButton.setText(_translate("MainWindow", "Gerar modelo"))
        self.split_box_anray_45_90.setText(_translate("MainWindow", "45/90"))
        self.split_box_anray_0_45.setText(_translate("MainWindow", "0/45"))
        self.split_box_anray_30_60.setText(_translate("MainWindow", "30/60"))
        self.split_box_anray_0_90.setText(_translate("MainWindow", "0/90"))
        self.label_34.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>10%</p><p>spit</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:600;\">10%<br/>Separação</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "HTI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Solo"))
        self.gridTabWidget_5.setTabText(self.gridTabWidget_5.indexOf(self.tab_anray_3), _translate("MainWindow", "Componentes/Anray"))
        self.Tmin.setText(_translate("MainWindow", "Tmin(s)"))
        self.Tmax.setText(_translate("MainWindow", "Tmax(s)"))
        self.label_23.setText(_translate("MainWindow", "dt(s)"))
        self.sismo_button.setText(_translate("MainWindow", "Plotar"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>Azimute<span style=\" vertical-align:super;\">(o)</span></p></body></html>"))
        self.radioButton_0.setText(_translate("MainWindow", "0"))
        self.radioButton_30.setText(_translate("MainWindow", "30"))
        self.radioButton_45.setText(_translate("MainWindow", "45"))
        self.radioButton_60.setText(_translate("MainWindow", "60"))
        self.radioButton_90.setText(_translate("MainWindow", "90"))
        self.label_42.setText(_translate("MainWindow", "Freq"))
        self.label_43.setText(_translate("MainWindow", "Gama"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Wavelet</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "|max (radial)|"))
        self.label_x_max.setText(_translate("MainWindow", "<html><head/><body><p>...</p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "|max|"))
        self.label_z_max.setText(_translate("MainWindow", "<html><head/><body><p>...</p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "|max (vertical)|"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Normalização</span></p><p align=\"center\"><span style=\" font-size:7pt;\">1/|max|</span></p></body></html>"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:6pt;\">Plotar apenas no primeiro geofone</span></p></body></html>"))
        self.checkBox_solo_sismo.setText(_translate("MainWindow", "Reflexão do solo"))
        self.gridTabWidget_5.setTabText(self.gridTabWidget_5.indexOf(self.tab_su), _translate("MainWindow", "Sismogramas"))
        self.radio_sismo_0_90.setText(_translate("MainWindow", "0/90"))
        self.radio_sismo_45_90.setText(_translate("MainWindow", "45/90"))
        self.radio_sismo_0_45.setText(_translate("MainWindow", "0/45"))
        self.radio_sismo_30_60.setText(_translate("MainWindow", "30/60"))
        self.label_46.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>10%</p><p>spit</p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:600;\">Azimutes</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "Componente"))
        self.radioButton_plot_x.setText(_translate("MainWindow", "radial"))
        self.radioButton_plot_z.setText(_translate("MainWindow", "vertical"))
        self.label_39.setText(_translate("MainWindow", "Tmax"))
        self.label_51.setText(_translate("MainWindow", "Tmin"))
        self.gridTabWidget_5.setTabText(self.gridTabWidget_5.indexOf(self.tab), _translate("MainWindow", "Sismogramas/Azimutes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

